---
- hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  vars:
    region: us-east-1
    ami_name: Sample
  tasks:
    - name: To Get AMI-Id
      command: "aws ec2 describe-images
                --filters Name=name,Values={{ ami_name }}
                --query 'Images[0].ImageId' --output text"
      register: imageid

    - name: To Delete an AMI
      ec2_ami:
        region: "{{ region }}"
        image_id: "{{ imageid.stdout }}"
        delete_snapshot: yes
        state: absent
      when: imageid.stdout!="None"

