- name: To Launch EC2 Instance
  hosts: localhost
  connection: local
  tasks:
  - name: Launching EC2 Instance
    ec2:
      instance_type: t2.micro
      key_name: Aws15-PrivateKey
      image: ami-035b3c7efe6d061d5
      region: us-east-1
      group: default
      count: 1
      vpc_subnet_id: subnet-9c2f0fb2
      wait: yes
      assign_public_ip: yes
